#!/bin/python
import os
import re

yamlpath = "src/python_interface_to_workflows/templates/"
yamllist: list[str] = []
for x in os.listdir(yamlpath):
    if x.endswith(".yaml"):
        yamllist.append(x)

for file in yamllist:
    z = 0
    with open(yamlpath + file) as s:
        filelist = s.readlines()
        cleanfilenames: list[str] = []
        for line in filelist:
            line = line.rstrip()
            cleanfilenames.append(line)
    api_ver = any(
        re.search(r"apiVersion:\sargoproj\.io\/v1alpha1", line)
        for line in cleanfilenames
    )
    clst_tmpt = any(
        re.search(r"kind:\sClusterWorkflowTemplate", line) for line in cleanfilenames
    )
    title = any(
        re.search(r"\s\s\s\sworkflows.argoproj.io/title:\s.+", line)
        for line in cleanfilenames
    )
    repo = any(
        re.search(r"\s\s\s\sworkflows.diamond.ac.uk/repository:\s.+", line)
        for line in cleanfilenames
    )
    group = any(
        re.search(r"\s\s\s\sworkflows.diamond.ac.uk/science-group-.+:\s.+", line)
        for line in cleanfilenames
    )
    gen_name = any(re.search(r"\s\sgenerateName:\s.+", line) for line in cleanfilenames)
    normal_name = any(re.search(r"^\s\sname:\s.+", line) for line in cleanfilenames)
    if api_ver and clst_tmpt and title and repo and group:
        if gen_name != normal_name:
            exit(0)
        else:
            print(
                "generated_name and normal_name error, must have one of these not both"
            )
            exit(1)
    else:
        print(f"""api_ver present?: {api_ver}
                cluster template present?: {clst_tmpt}
                title present?: {title}
                repository present?: {repo}
                group present?: {group}""")
        exit(1)
